// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/documents": {
    params: {};
  };
  "/classes": {
    params: {};
  };
  "/ficha/:id": {
    params: {
      "id": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/documents" | "/classes" | "/ficha/:id" | "/auth/login" | "/auth/register";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/documents.tsx": {
    id: "routes/documents";
    page: "/documents";
  };
  "routes/classes.tsx": {
    id: "routes/classes";
    page: "/classes";
  };
  "routes/rpgSheet.tsx": {
    id: "routes/rpgSheet";
    page: "/ficha/:id";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/auth/register";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/documents": typeof import("./app/routes/documents.tsx");
  "routes/classes": typeof import("./app/routes/classes.tsx");
  "routes/rpgSheet": typeof import("./app/routes/rpgSheet.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
};