"""empty message

Revision ID: 5456a88c075d
Revises: 858fb6a89f07
Create Date: 2026-06-27 23:37:22.600771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5456a88c075d'
down_revision = '858fb6a89f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_quantity', sa.Integer(), nullable=True, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('max_quantity')

    # ### end Alembic commands ###
