"""empty message

Revision ID: 638ec8207cf3
Revises: 5456a88c075d
Create Date: 2026-06-28 00:25:39.616263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638ec8207cf3'
down_revision = '5456a88c075d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('hidden')
        batch_op.drop_column('temporary')

    # ### end Alembic commands ###
