"""empty message

Revision ID: 858fb6a89f07
Revises: 
Create Date: 2026-06-27 22:04:22.840752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858fb6a89f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('att_inventory_capacity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('offset_inventory_capacity', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_inventory_capacity', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('base_inventory_capacity')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('offset_inventory_capacity')
        batch_op.drop_column('att_inventory_capacity')

    # ### end Alembic commands ###
